---
title: Serene scene
hero_image: images/serene-banner.png
description: Create a peaceful forest scene for you to look at, listen to, and relax
  with
version: 4
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: Introduction
  completion: engaged
- title: Grow a tree
- title: Colour the flowers
- title: Set the scene
- title: Make the fauna move
  completion: internal
- title: Add more
- title: Share
- title: What next?
