title: Serene scene
hero_image: images/serene-banner.png
description: Create a peaceful forest scene for you to look at, listen to, and relax with
version: 4
listed: false
copyedit: false
last_tested: "2020-05-21"
steps:
  - title: Introduction
  - title: Grow a tree
  - title: Colour the flowers
  - title: Set the scene
  - title: Add some fauna
  - title: "Challenge: add a dragonfly"
    challenge: true
  - title: Share your project
  - title: "What next?"
